#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: task-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: task-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 3Gi
#
---
apiVersion: v1
kind: Pod
metadata:
  name: hdfs
spec:
  containers:
    - name: hadoop
      image: harisekhon/hadoop
      imagePullPolicy: Never
      ports:
        - containerPort: 50075
          name: "namenode"
        - containerPort: 50070
          name: "datanode"
#        - 8088
#        - 8020
#        - 50075
#        - 50070
      volumeMounts:
        - mountPath: "/home/hadoop/data/dataNode"
          name: hadoop-storage
#volumes:
#  - hdfs:
#  - ./hdfs_config:/hadoop/etc/hadoop/hdfs-site.xml
