apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  selector:
    matchLabels:
      run: converter
  replicas: 1
  template:
    metadata:
      labels:
        run: converter
    spec:
      containers:
      - name: converter
        image: converter
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: converter
  labels:
    run: converter
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: converter